# Generated by Django 5.2.2 on 2025-08-21 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('status', models.CharField(choices=[('passed', 'Đã hoàn thành'), ('studying', 'Đang học'), ('not_started', 'Chưa học')], max_length=50)),
                ('register_status', models.CharField(choices=[('registered', 'Đã đăng ký'), ('not_register', 'Chưa đăng ký')], max_length=50)),
            ],
            options={
                'db_table': 'course_module',
            },
        ),
        migrations.CreateModel(
            name='RecommendDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommend_book',
            },
        ),
        migrations.CreateModel(
            name='StudentsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.IntegerField()),
                ('student_id', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'account_students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='ListLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='home.coursemodule')),
            ],
            options={
                'db_table': 'list_lesson',
            },
        ),
        migrations.CreateModel(
            name='RecommendCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('status', models.CharField(choices=[('passed', 'Đã hoàn thành'), ('studying', 'Đang học'), ('not_started', 'Chưa học')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentsaccount')),
            ],
            options={
                'db_table': 'mycourse',
            },
        ),
    ]
